service: sls-demo

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: sls-cli
  region: eu-west-3

functions:
  templates:
    handler: handler.themes
    events:
      - http:
          method: get
          path: /getThemes
